#index:
##    path: /
##    controller: App\Controller\DefaultController::index
#usuarios
user:
    path: /usuario
    controller: App\Controller\UserController::index
#video
video:
    path: /video
    controller: App\Controller\VideoController::index
