#index:
##    path: /
##    controller: App\Controller\DefaultController::index
#usuarios
user:
    path: /usuario
    controller: App\Controller\UserController::index
    methods: [POST]

register:
    path: /register
    controller: App\Controller\UserController::create
    methods: [POST]

login:
    path: /login
    controller: App\Controller\UserController::login
    methods: [POST]

user_edit:
    path: user/edit
    controller: App\Controller\UserController::edit
    methods: [PUT]

#video
video:
    path: /video
    controller: App\Controller\VideoController::index

video_new:
    path: /video/nuevo
    controller: App\Controller\VideoController::create
    methods: [POST]

video_list:
    path: /video/listado
    controller: App\Controller\VideoController::videos
    methods: [GET]
